# FADE 15/17 (hide/cull): PEN holder plates (6 vols).
# Hides this component (culled from the render) -> reveals the LMFE.
# Run fade1..fade17 in order to melt the array away from outside in.
/vis/geometry/set/visibility pen_large 0 false
/vis/geometry/set/visibility pen_medium 0 false
/vis/geometry/set/visibility pen_medium_ortec 0 false
/vis/geometry/set/visibility pen_ppc_small 0 false
/vis/geometry/set/visibility pen_small 0 false
/vis/geometry/set/visibility pen_xlarge 0 false
